#!mule
agents:
  - name: deb-amd64
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=amd64
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=$GIT_BRANCH
    workDir: $HOME/projects/go-algorand

  - name: deb-arm64
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=amd64
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=$GIT_BRANCH
    workDir: $HOME/projects/go-algorand

  - name: rpm-amd64
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=amd64
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=$GIT_BRANCH
    workDir: $HOME/projects/go-algorand

  - name: rpm-arm64
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/go-algorand-ci-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=arm64
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=$GIT_BRANCH
    workDir: $HOME/projects/go-algorand

  - name: alpine
    dockerFilePath: docker/build/cicd.alpine.Dockerfile
    image: algorand/go-algorand-ci-linux
    version: scripts/configure_dev-deps.sh
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=${GIT_BRANCH}
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
      - ARCH=arm32v6
    workDir: $HOME/projects/go-algorand

  - name: docker
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    image: algorand/go-algorand-docker-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - NETWORK=$NETWORK
      - VERSION=$VERSION
      - TRAVIS_BRANCH=$GIT_BRANCH
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: build-amd64
    agent: deb-amd64
    target: ci-build

  - task: docker.Make
    name: build-arm64
    agent: deb-arm64
    target: ci-build

  - task: docker.Make
    name: build-arm
    agent: alpine
    target: ci-build

  - task: docker.Make
    name: rpm-amd64
    agent: rpm-amd64
    target: mule-package-rpm

  - task: docker.Make
    name: deb-amd64
    agent: deb-amd64
    target: mule-package-deb

  - task: docker.Make
    name: deb-arm64
    agent: deb-arm64
    target: mule-package-deb

  - task: docker.Make
    name: rpm-arm64
    agent: rpm-arm64
    target: mule-package-rpm

  - task: docker.Make
    name: docker
    agent: docker
    target: mule-package-docker

  - task: s3.BucketCopy
    name: amd64
    src: ./tmp/node_pkgs/linux/amd64
    dest: s3://algorand-staging/releases/beta/2.4.0/

  - task: s3.BucketCopy
    name: arm
    src: ./tmp/node_pkgs/linux/arm
    dest: s3://algorand-staging/releases/beta/2.4.0/

  - task: s3.BucketCopy
    name: arm64
    src: ./tmp/node_pkgs/linux/arm64
    dest: s3://algorand-staging/releases/beta/2.4.0/

jobs:
  package-amd64:
    tasks:
      - docker.Make.build-amd64
      - docker.Make.deb-amd64
      - docker.Make.rpm-amd64
      - docker.Make.docker
      - s3.BucketCopy.amd64

  package-arm64:
    tasks:
      - docker.Make.build-arm64
      - docker.Make.deb-arm64
        #      - docker.Make.rpm-arm64
      - s3.BucketCopy.arm64

  package-arm:
    tasks:
      - docker.Make.build-arm
      - docker.Make.deb-amd64
      - docker.Make.rpm-amd64
      - s3.BucketCopy.arm

