#!mule
agents:
  - name: signer
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - GPG_DIR=$GPG_DIR
      - NETWORK=$NETWORK
      - S3_SOURCE=$S3_SOURCE
      - VERSION=$VERSION
    volumes:
      - $XDG_RUNTIME_DIR/gnupg/S.gpg-agent:/root/.gnupg/S.gpg-agent
      - $HOME/.gnupg/pubring.kbx:/root/.gnupg/pubring.kbx
    workDir: $HOME/projects/go-algorand

  - name: tester-deb
    dockerFilePath: docker/build/cicd.ubuntu.Dockerfile
    image: algorand/go-algorand-ci-linux-ubuntu
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BRANCH=$BRANCH
      - NETWORK=$NETWORK
      - S3_SOURCE=$S3_SOURCE
      - SHA=$SHA
      - VERSION=$VERSION
    workDir: $HOME/projects/go-algorand

  - name: tester-rpm
    dockerFilePath: docker/build/cicd.centos.Dockerfile
    image: algorand/mule-linux-centos
    version: scripts/configure_dev-deps.sh
    buildArgs:
      - GOLANG_VERSION=`./scripts/get_golang_version.sh`
    env:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BRANCH=$BRANCH
      - NETWORK=$NETWORK
      - S3_SOURCE=$S3_SOURCE
      - SHA=$SHA
      - VERSION=$VERSION
    workDir: $HOME/projects/go-algorand

tasks:
  - task: docker.Make
    name: package-sign
    agent: signer
    target: mule-sign

  - task: docker.Make
    name: package-test-deb
    agent: tester-deb
    target: mule-test-deb

  - task: docker.Make
    name: package-test-rpm
    agent: tester-rpm
    target: mule-test-rpm

  - task: s3.BucketCopy
    name: amd64
    src: $HOME/projects/go-algorand/tmp/node_pkgs/linux/amd64
    dest: s3://$STAGING/$CHANNEL/$VERSION/

  - task: s3.BucketCopy
    name: arm
    src: $HOME/projects/go-algorand/tmp/node_pkgs/linux/arm
    dest: s3://$STAGING/$CHANNEL/$VERSION/

  - task: s3.BucketCopy
    name: arm64
    src: $HOME/projects/go-algorand/tmp/node_pkgs/linux/arm64
    dest: s3://$STAGING/$CHANNEL/$VERSION/

jobs:
  package-sign:
    tasks:
      - docker.Make.package-sign

  package-test:
    tasks:
      - docker.Make.package-test-deb
      - docker.Make.package-test-rpm

  package-upload:
    tasks:
      - s3.BucketCopy.amd64
      - s3.BucketCopy.arm
      - s3.BucketCopy.arm64

